[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "gotenberg"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[[services]]
internal_port = 3000
protocol = "tcp"
